version: '3'
services:
  mongo:
    image: 'mongo:5.0.19'
    container_name: loja_db
    ports:
      - "27017:27017"
    volumes:
      - /tmp/loja/mongo:/data/db
    networks:
      - loja-network
  loja:
    depends_on:
      - mongo
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/loja
    networks:
      - loja-network

networks:
  loja-network:
    driver: bridge
