name: Quebra tudo Jacoco

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  sonarcloud:
    name: Run Jacoco analysis
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven and run tests
        run: mvn clean verify
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-coverage-report
          path: target/site/jacoco/index.html

      # 6. Checar a cobertura e falhar se for abaixo de 80%
      - name: Check coverage
        run: |
          mvn jacoco:report \
          
          COVERAGE=$(mvn jacoco:report | grep -oP 'TOTAL\s+\d+\s+\d+\.\d+\s+\d+\.\d+\s+\K\d+\.\d+(?=%)' | head -n 1) \
#
#          if [ -z "$COVERAGE" ]; then
#          echo "Não foi possível extrair a cobertura de código."
#          exit 1
#          fi \
#
#          echo "Coverage: $COVERAGE%"
#
#          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
#            echo "Code coverage is below 80%. Failing the PR."
#            exit 1
#          fi